In [4]:
import numpy as np


In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr2 = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [12]:
arr2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [14]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])

In [15]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [18]:
arr1 ** arr2 


array([[   1,    4,   27,  256, 3125],
       [   1,   16,   27,   16,    5]])

---------------------


In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.arange(1,81,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76])

In [33]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])