In [12]:
import numpy as np 


In [3]:
arr = np.array([[1,2,3],[3,2,1],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
flat_array = arr.flatten()

In [8]:
flat_array

array([1, 2, 3, 3, 2, 1, 4, 5, 6, 7, 8, 9])

In [11]:
flat_array[0]

np.int64(1)

In [14]:
flat_array[3:6]

array([3, 2, 1])

In [16]:
flat_array[:7]

array([1, 2, 3, 3, 2, 1, 4])

In [18]:
flat_array[6:]

array([4, 5, 6, 7, 8, 9])

Changing an element in the instance created by the array slicing also change on its original one too 
as slicing returns an view not an copy this is the feature of numpy 

In [20]:
new_array = flat_array[3:8]

In [22]:
new_array

array([3, 2, 1, 4, 5])

In [23]:
new_array[1]= 12345


In [25]:
new_array

array([    3, 12345,     1,     4,     5])

In [26]:
flat_array

array([    1,     2,     3,     3, 12345,     1,     4,     5,     6,
           7,     8,     9])

### to make a copy use .copy()

In [28]:
new2 = flat_array[2:8].copy()

In [29]:
new2

array([    3,     3, 12345,     1,     4,     5])

In [32]:
new2[2] = 2

In [34]:
new2

array([3, 3, 2, 1, 4, 5])

In [35]:
flat_array

array([    1,     2,     3,     3, 12345,     1,     4,     5,     6,
           7,     8,     9])

----------------------------------------

In [38]:
flat_array[flat_array>4] #satisfy condition

array([12345,     5,     6,     7,     8,     9])