In [27]:
import numpy as np 
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.mean() – Compute the mean (average) of an array.

In [13]:
np.mean(arr)



np.float64(3.0)

np.std() – Compute the standard deviation of an array.

In [14]:
np.std(arr)

np.float64(1.4142135623730951)

np.var(arr) - Compute the variance of an array 

In [15]:
np.var(arr)

np.float64(2.0)

np.min() - Compute the minimum value of an array 

In [16]:
np.min(arr)

np.int64(1)

np.max() - Compute the maximum value of an array 

In [17]:
np.max(arr)

np.int64(5)

np.sum() -Compute the sum of all elements in an array

In [18]:
np.sum(arr)

np.int64(15)

np.prod() - compute the product of all elements in an array/


In [19]:
np.prod(arr)

np.int64(120)

np.median() - Compute the median of an array 

In [20]:
np.median(arr)

np.float64(3.0)

np.percentile() - Compute the percentile of an array

In [21]:
np.percentile(arr,50)  #for the 50th percentile

np.float64(3.0)

np.argmin() - return the index of minimum value in an array

In [22]:
np.argmin(arr)

np.int64(0)

np.argmax() - return the index of maximum value in an array 

In [23]:
np.argmax(arr)

np.int64(4)

np.corrcoef() - compute the correlation coefficient matrix of two arrays

In [28]:
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

np.unique() - find the unique elements of an array

In [29]:
np.unique(arr)

array([1, 2, 3, 4, 5])

np.diff() - Compute the nth differnces of an array

In [30]:
np.diff(arr)

array([1, 1, 1, 1])

np.cumsum() - Compute the cumulative sum of an array

In [31]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

np.linspace() - Create an array with evenly spaced number over a specific interval

In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

np.log() -compute the natural logarithm of an array

In [33]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

np.exp() - Compute the exponential of an array

In [34]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])