In [2]:
import numpy as np 

In [20]:
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,0]])

In [5]:
arr1.ndim  # dimension

2

In [6]:
arr1.shape #shape of array 

(3, 3)

In [8]:
arr1.size #size total elements

9

In [10]:
arr1.dtype #data type 

dtype('int64')

In [12]:
arr2 = np.array([arr1], dtype='float32')

In [14]:
arr2

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)

In [15]:
arr2.dtype

dtype('float32')

In [16]:
arr3 = arr2.astype('float64')

In [17]:
arr3.dtype

dtype('float64')

In [23]:
reshaped_array = arr1.reshape((3,4)) # can only be done if it implies on all elements

In [25]:
reshaped_array #after reshaping

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [26]:
arr1 #before 

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [28]:
flat_array = arr1.flatten() # convert into 1-D array

In [29]:
flat_array

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 0])